create table roles
(
    id             bigint generated by default as identity
        primary key,
    code           varchar(50)  not null
        constraint ukch1113horj4qr56f91omojv8
            unique,
    created_at     timestamp(6),
    description    text,
    is_system_role boolean      not null,
    name           varchar(100) not null,
    updated_at     timestamp(6)
);

alter table roles
    owner to pets_admin;

create table trending_stats
(
    id           bigint generated by default as identity
        primary key,
    hashtag      varchar(255) not null
        constraint ukmkh2y9jqwy2np3jou9s9rtkif
            unique,
    last_updated timestamp(6),
    post_count   bigint,
    search_count bigint,
    view_count   bigint
);

alter table trending_stats
    owner to pets_admin;

create table users
(
    id                   bigint generated by default as identity
        primary key,
    address              varchar(255),
    avatar_url           varchar(500) not null,
    bio                  text,
    city                 varchar(100),
    cover_url            varchar(500),
    created_at           timestamp(6),
    district             varchar(100),
    email                varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    full_name            varchar(255) not null,
    is_verified          boolean      not null,
    kyc_document_url     varchar(500),
    kyc_status           varchar(20)
        constraint users_kyc_status_check
            check ((kyc_status)::text = ANY
                   ((ARRAY ['UNVERIFIED'::character varying, 'PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying])::text[])),
    last_login_at        timestamp(6),
    latitude             double precision,
    login_provider       varchar(255) not null
        constraint users_login_provider_check
            check ((login_provider)::text = ANY
                   ((ARRAY ['EMAIL'::character varying, 'GOOGLE'::character varying, 'FACEBOOK'::character varying, 'PHONE'::character varying])::text[])),
    longitude            double precision,
    must_change_password boolean      not null,
    password_hash        varchar(255) not null,
    phone_number         varchar(20),
    status               varchar(255) not null
        constraint users_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'SUSPENDED'::character varying, 'BANNED'::character varying, 'DELETED'::character varying])::text[])),
    updated_at           timestamp(6),
    role_id              bigint       not null
        constraint fkp56c1712k691lhsyewcssf40f
            references roles
);

alter table users
    owner to pets_admin;

create table conversations
(
    id              bigint generated by default as identity
        primary key,
    group_avatar    text,
    group_name      varchar(255),
    is_group_chat   boolean,
    updated_at      timestamp(6) not null,
    created_by_id   bigint
        constraint fkq33k2jsvt4rvxsbfcqn5723x8
            references users,
    last_message_id bigint
        constraint ukbap2ig9x1dq1y1revhfjkk64l
            unique,
    user_one_id     bigint       not null
        constraint fk6fmlr7r40yaqretwu07dt86d4
            references users,
    user_two_id     bigint
        constraint fksjcfd6rwy4gfdgc0ncup74e1p
            references users
);

alter table conversations
    owner to pets_admin;

create table conversation_members
(
    id              bigint generated by default as identity
        primary key,
    joined_at       timestamp(6),
    role            varchar(50)
        constraint conversation_members_role_check
            check ((role)::text = ANY ((ARRAY ['ADMIN'::character varying, 'MEMBER'::character varying])::text[])),
    conversation_id bigint not null
        constraint fknxfbup81m9td8l03se3rg2icf
            references conversations,
    user_id         bigint not null
        constraint fkosvpesom2hosqrhos0cf6uel0
            references users
);

alter table conversation_members
    owner to pets_admin;

create table friend_requests
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6) not null,
    responded_at timestamp(6),
    status       varchar(255) not null
        constraint friend_requests_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying])::text[])),
    receiver_id  bigint       not null
        constraint fktcmqalc5v4qdt1slgcsa544i5
            references users,
    sender_id    bigint       not null
        constraint fkcchlh48b4347amfvmke793bg7
            references users
);

alter table friend_requests
    owner to pets_admin;

create table friendships
(
    id          bigint generated by default as identity
        primary key,
    accepted_at timestamp(6),
    created_at  timestamp(6),
    status      varchar(50) not null
        constraint friendships_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'ACCEPTED'::character varying, 'BLOCKED'::character varying])::text[])),
    friend_id   bigint      not null
        constraint fkt0mh1j446gu5rqba17rnknuil
            references users,
    user_id     bigint      not null
        constraint fk4mcscxflf13uk72aupf6uwbgn
            references users,
    constraint ukjwaac0iw9d1fu58mx7afwf9f4
        unique (user_id, friend_id)
);

alter table friendships
    owner to pets_admin;

create table groups
(
    id              bigint generated by default as identity
        primary key,
    avatar_url      varchar(500),
    category        varchar(100)
        constraint groups_category_check
            check ((category)::text = ANY
                   ((ARRAY ['BREED'::character varying, 'LOCATION'::character varying, 'INTEREST'::character varying, 'ACTIVITY'::character varying, 'OTHER'::character varying])::text[])),
    city            varchar(100),
    cover_image_url varchar(500),
    created_at      timestamp(6),
    description     text,
    district        varchar(100),
    is_active       boolean      not null,
    is_private      boolean      not null,
    member_count    integer      not null,
    name            varchar(255) not null,
    post_count      integer      not null,
    rules           text,
    slug            varchar(255) not null
        constraint ukiv95crpat83rqqgixej9uhm9m
            unique,
    updated_at      timestamp(6),
    creator_id      bigint
        constraint fkjq37pdrj0mtih03a22mc7noun
            references users
);

alter table groups
    owner to pets_admin;

create table group_members
(
    id        bigint generated by default as identity
        primary key,
    joined_at timestamp(6),
    role      varchar(50) not null
        constraint group_members_role_check
            check ((role)::text = ANY
                   ((ARRAY ['ADMIN'::character varying, 'MODERATOR'::character varying, 'MEMBER'::character varying, 'PENDING'::character varying])::text[])),
    group_id  bigint      not null
        constraint fkkv9vlrye4rmhqjq4qohy2n5a6
            references groups,
    user_id   bigint      not null
        constraint fknr9qg33qt2ovmv29g4vc3gtdx
            references users,
    constraint ukp940p7g0r9yihubnf6rtaheog
        unique (group_id, user_id)
);

alter table group_members
    owner to pets_admin;

create table messages
(
    id              bigint generated by default as identity
        primary key,
    content         text         not null,
    created_at      timestamp(6) not null,
    edited_at       timestamp(6),
    image           text,
    is_deleted      boolean,
    is_edited       boolean,
    is_read         boolean      not null,
    is_recalled     boolean,
    post_id         bigint,
    read_at         timestamp(6),
    conversation_id bigint       not null
        constraint fkt492th6wsovh1nush5yl5jj8e
            references conversations,
    reply_to_id     bigint
        constraint fkg23x99if9xk265onv7btb0cg9
            references messages,
    sender_id       bigint       not null
        constraint fk4ui4nnwntodh6wjvck53dbk9m
            references users
);

alter table messages
    owner to pets_admin;

alter table conversations
    add constraint fkd9sy3cjuppb511olt5pv3ixe
        foreign key (last_message_id) references messages;

create table message_reactions
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    emoji      varchar(10) not null,
    message_id bigint      not null
        constraint fk1o714y33gam6b6741ci4ho041
            references messages,
    user_id    bigint      not null
        constraint fkoip2ttlg2py976foointttaew
            references users,
    constraint uk97x64hflnew8pcu67n1bky803
        unique (message_id, user_id, emoji)
);

alter table message_reactions
    owner to pets_admin;

create table notifications
(
    id           bigint generated by default as identity
        primary key,
    content      text         not null,
    created_at   timestamp(6) not null,
    from_user_id bigint,
    is_read      boolean      not null,
    link         varchar(255),
    post_id      bigint,
    title        varchar(255) not null,
    type         varchar(255) not null
        constraint notifications_type_check
            check ((type)::text = ANY
                   ((ARRAY ['COMMENT'::character varying, 'MESSAGE'::character varying, 'LIKE'::character varying, 'POST_UPDATED'::character varying, 'PET_FOUND'::character varying, 'GROUP_POST'::character varying, 'GROUP_UPDATE'::character varying, 'GROUP_MEMBER'::character varying, 'ORG_POST'::character varying, 'SYSTEM'::character varying])::text[])),
    user_id      bigint       not null
        constraint fk9y21adhxn0ayjhfocscqox7bh
            references users
);

alter table notifications
    owner to pets_admin;

create table organizations
(
    id             bigint generated by default as identity
        primary key,
    address        varchar(255) not null,
    city           varchar(255) not null,
    contact_name   varchar(255),
    created_at     timestamp(6),
    description    text,
    district       varchar(255),
    email          varchar(255) not null,
    follower_count integer      not null,
    is_verified    boolean,
    logo           varchar(255),
    name           varchar(255) not null,
    phone          varchar(255) not null,
    updated_at     timestamp(6),
    website        varchar(255),
    user_id        bigint
        constraint uksx0dx8uvgb81d6ryhi7vi36dt
            unique
        constraint fki6hsrnbrm13v8smtg37nogkx5
            references users
);

alter table organizations
    owner to pets_admin;

create table follows
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6),
    followed_user_id bigint
        constraint fkfg3bo4whthco31ewoiaxpjhvi
            references users,
    follower_id      bigint not null
        constraint fkqnkw0cwwh6572nyhvdjqlr163
            references users,
    organization_id  bigint
        constraint fk5or8l0xh5cjrnkf2exx7a095h
            references organizations,
    constraint uk5l4614hjxewv1k2ljd5tag3w
        unique (follower_id, organization_id),
    constraint uk759pqgqg2gqkxn7mrr27b2smm
        unique (follower_id, followed_user_id)
);

alter table follows
    owner to pets_admin;

create table pets
(
    id            bigint generated by default as identity
        primary key,
    age           integer      not null,
    bio           text,
    breed         varchar(255) not null,
    color         varchar(255),
    created_at    timestamp(6) not null,
    gender        varchar(255) not null
        constraint pets_gender_check
            check ((gender)::text = ANY ((ARRAY ['MALE'::character varying, 'FEMALE'::character varying])::text[])),
    is_neutered   boolean      not null,
    is_vaccinated boolean      not null,
    name          varchar(255) not null,
    personality   jsonb,
    profile_photo varchar(255),
    size          varchar(255)
        constraint pets_size_check
            check ((size)::text = ANY
                   ((ARRAY ['SMALL'::character varying, 'MEDIUM'::character varying, 'LARGE'::character varying])::text[])),
    special_needs text,
    type          varchar(255) not null,
    updated_at    timestamp(6),
    weight        double precision,
    user_id       bigint       not null
        constraint fkc47kjb41qf50bwgddm024m5xn
            references users
);

alter table pets
    owner to pets_admin;

create table adoption_applications
(
    id               bigint generated by default as identity
        primary key,
    application_data jsonb,
    created_at       timestamp(6) not null,
    status           varchar(255) not null
        constraint adoption_applications_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'REVIEWING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying])::text[])),
    updated_at       timestamp(6) not null,
    applicant_id     bigint       not null
        constraint fkvw031wcwn8gl97r8pmu63ntk
            references users,
    owner_id         bigint       not null
        constraint fkjr0lix79415kg0seyavjvne5f
            references users,
    pet_id           bigint       not null
        constraint fkngtgolq4ramak2fvoc9ebm9qm
            references pets
);

alter table adoption_applications
    owner to pets_admin;

create table fundraising_campaigns
(
    id                   bigint generated by default as identity
        primary key,
    beneficiary          varchar(255),
    category             varchar(50)    not null
        constraint fundraising_campaigns_category_check
            check ((category)::text = ANY
                   ((ARRAY ['MEDICAL'::character varying, 'RESCUE'::character varying, 'SHELTER'::character varying, 'FOOD'::character varying, 'OTHER'::character varying])::text[])),
    created_at           timestamp(6)   not null,
    currency             varchar(10)    not null,
    current_amount       numeric(15, 2) not null,
    description          text           not null,
    description_detailed text,
    end_date             timestamp(6),
    image                varchar(500)   not null,
    slug                 varchar(255)   not null
        constraint ukng9unncynvbwtutmllrljpxke
            unique,
    start_date           timestamp(6)   not null,
    status               varchar(20)    not null
        constraint fundraising_campaigns_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'PAUSED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])),
    target_amount        numeric(15, 2) not null,
    title                varchar(255)   not null,
    updated_at           timestamp(6)   not null,
    pet_id               bigint
        constraint fk6wkg1aycaugaoa9243gmhqr2i
            references pets,
    user_id              bigint         not null
        constraint fkk55bkfumx33xch5qyqxsch5rr
            references users
);

alter table fundraising_campaigns
    owner to pets_admin;

create table campaign_updates
(
    id          bigint generated by default as identity
        primary key,
    content     text         not null,
    created_at  timestamp(6) not null,
    images      jsonb,
    title       varchar(255) not null,
    campaign_id bigint       not null
        constraint fkjok6c8pns4xmcd1xknyo8g407
            references fundraising_campaigns
);

alter table campaign_updates
    owner to pets_admin;

create table donations
(
    id                     bigint generated by default as identity
        primary key,
    amount                 numeric(15, 2) not null,
    created_at             timestamp(6)   not null,
    currency               varchar(10)    not null,
    is_anonymous           boolean        not null,
    message                text,
    payment_method         varchar(20)    not null
        constraint donations_payment_method_check
            check ((payment_method)::text = ANY
                   ((ARRAY ['MOMO'::character varying, 'ZALOPAY'::character varying, 'BANK'::character varying, 'CARD'::character varying])::text[])),
    payment_transaction_id varchar(100),
    status                 varchar(20)    not null
        constraint donations_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])),
    campaign_id            bigint         not null
        constraint fkmm6m0pe0xmhbov9i1g4hkckvp
            references fundraising_campaigns,
    donor_id               bigint
        constraint fkp8lwp38vg4a0v2y69d2krn562
            references users
);

alter table donations
    owner to pets_admin;

create table pet_health_records
(
    id           bigint generated by default as identity
        primary key,
    allergies    jsonb,
    created_at   timestamp(6) not null,
    last_checkup timestamp(6),
    notes        text,
    updated_at   timestamp(6) not null,
    weight       double precision,
    pet_id       bigint       not null
        constraint ukkwrqcwb8txkyx9kuq41k7ggql
            unique
        constraint fk2f2gc5sgpqdyk6ot69lhjvlcq
            references pets,
    user_id      bigint       not null
        constraint fkciwps67rto2od30ugwb76si4e
            references users
);

alter table pet_health_records
    owner to pets_admin;

create table medical_history
(
    id               bigint generated by default as identity
        primary key,
    clinic           varchar(255),
    condition        varchar(255) not null,
    cost             double precision,
    created_at       timestamp(6) not null,
    notes            text,
    treatment        text         not null,
    veterinarian     varchar(255),
    visit_date       timestamp(6) not null,
    weight           double precision,
    health_record_id bigint       not null
        constraint fk282t2lhojtp328rrkxd25xar6
            references pet_health_records
);

alter table medical_history
    owner to pets_admin;

create table pet_posts
(
    id              bigint generated by default as identity
        primary key,
    approval_status varchar(255)
        constraint pet_posts_approval_status_check
            check ((approval_status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])),
    city            varchar(255) not null,
    created_at      timestamp(6) not null,
    description     text         not null,
    district        varchar(255),
    featured        boolean      not null,
    group_ids       jsonb,
    image           varchar(255),
    is_active       boolean      not null,
    latitude        double precision,
    location        varchar(255),
    longitude       double precision,
    meta            jsonb,
    pet_type        varchar(255) not null,
    post_type       varchar(255) not null
        constraint pet_posts_post_type_check
            check ((post_type)::text = ANY
                   ((ARRAY ['LOST_FOUND'::character varying, 'ADOPTION'::character varying, 'REVIEW'::character varying, 'QNA'::character varying, 'TIP'::character varying, 'BREEDING'::character varying, 'MARKETPLACE'::character varying])::text[])),
    slug            varchar(255) not null
        constraint uk4p1l09jel3ojqjbysk6mtjl6f
            unique,
    status          varchar(255) not null
        constraint pet_posts_status_check
            check ((status)::text = ANY
                   ((ARRAY ['LOST'::character varying, 'FOUND'::character varying, 'FOR_ADOPTION'::character varying, 'RESCUE'::character varying, 'GENERAL'::character varying])::text[])),
    tags            jsonb,
    title           varchar(255) not null,
    updated_at      timestamp(6) not null,
    views           integer      not null,
    visibility_type integer      not null,
    group_id        bigint
        constraint fkg94ox99g4it5vts8pxnaohub
            references groups,
    pet_id          bigint
        constraint fkf9vyt3xxpn87ov9ij28fjhpb
            references pets,
    user_id         bigint       not null
        constraint fk88tq4q0x7wc4y732g468lckw9
            references users
);

alter table pet_posts
    owner to pets_admin;

create table comments
(
    id                bigint generated by default as identity
        primary key,
    content           text         not null,
    created_at        timestamp(6) not null,
    depth             integer      not null,
    is_active         boolean      not null,
    likes             integer      not null,
    parent_comment_id bigint
        constraint fk7h839m3lkvhbyv3bcdv7sm4fj
            references comments,
    updated_at        timestamp(6) not null,
    post_id           bigint       not null
        constraint fkdnvcooselkjo9xc2ctj571xgv
            references pet_posts,
    user_id           bigint       not null
        constraint fk8omq0tc18jd43bu5tjh6jvraq
            references users
);

alter table comments
    owner to pets_admin;

create table favorites
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) not null,
    post_id    bigint       not null
        constraint fk7e4ocsusgn36rg2wbmst5l9tn
            references pet_posts,
    user_id    bigint       not null
        constraint fkk7du8b8ewipawnnpg76d55fus
            references users
);

alter table favorites
    owner to pets_admin;

create table media
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6) not null,
    image_url    varchar(500) not null,
    is_thumbnail boolean      not null,
    pet_id       bigint
        constraint fkg6kblx2x7xl8w9a42e0itor0h
            references pets,
    post_id      bigint
        constraint fkukli1a52dk08ksvygybi5tg9
            references pet_posts
);

alter table media
    owner to pets_admin;

create table reactions
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) not null,
    type       varchar(255) not null
        constraint reactions_type_check
            check ((type)::text = ANY
                   ((ARRAY ['LIKE'::character varying, 'LOVE'::character varying, 'CARE'::character varying])::text[])),
    post_id    bigint       not null
        constraint fk1cnuh0nwvq5nomc4jum9d7mvy
            references pet_posts,
    user_id    bigint       not null
        constraint fkqmewaibcp5bxtlqxc2cawhuln
            references users,
    constraint ukaeq6cssia730m2nihyav05ui1
        unique (user_id, post_id)
);

alter table reactions
    owner to pets_admin;

create table refresh_tokens
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) not null,
    expiry_date timestamp(6) not null,
    token       varchar(255) not null
        constraint ukghpmfn23vmxfu3spu3lfg4r2d
            unique,
    user_id     bigint       not null
        constraint uk7tdcd6ab5wsgoudnvj7xf1b7l
            unique
        constraint fk1lih5y2npsf8u5o3vhdb9y0os
            references users
);

alter table refresh_tokens
    owner to pets_admin;

create table reports
(
    id               bigint generated by default as identity
        primary key,
    content          text         not null,
    created_at       timestamp(6) not null,
    responded_at     timestamp(6),
    responded_by     varchar(100),
    response_content text,
    status           varchar(255) not null
        constraint reports_status_check
            check ((status)::text = ANY
                   ((ARRAY ['CREATED'::character varying, 'RESOLVED'::character varying, 'REFUSED'::character varying])::text[])),
    target_id        bigint       not null
        constraint fk3lk2nhp7bkbop0hnurpdwfb3u
            references organizations,
    target_type      varchar(255) not null
        constraint reports_target_type_check
            check ((target_type)::text = ANY
                   ((ARRAY ['USER'::character varying, 'POST'::character varying, 'ORGANIZATION'::character varying])::text[])),
    updated_at       timestamp(6) not null,
    reporter_id      bigint       not null
        constraint fkd3qiw2om5d2oh5xb7fbdcq225
            references users
);

alter table reports
    owner to pets_admin;

create table rescue_centers
(
    id           bigint generated by default as identity
        primary key,
    address      varchar(255)     not null,
    city         varchar(255)     not null,
    created_at   timestamp(6)     not null,
    description  text,
    district     varchar(255),
    email        varchar(255),
    hours        varchar(100),
    is_verified  boolean          not null,
    latitude     double precision not null,
    longitude    double precision not null,
    name         varchar(255)     not null,
    phone        varchar(20)      not null,
    photos       jsonb,
    rating       double precision not null,
    review_count integer          not null,
    services     jsonb,
    specialties  jsonb,
    updated_at   timestamp(6)     not null,
    website      varchar(255),
    user_id      bigint
        constraint fkfo0pr28utmr4pa5m9qhj4hsyl
            references users
);

alter table rescue_centers
    owner to pets_admin;

create table rescue_center_reviews
(
    id               bigint generated by default as identity
        primary key,
    comment          text,
    created_at       timestamp(6) not null,
    rating           integer      not null,
    rescue_center_id bigint       not null
        constraint fkl0jpixjwsxpg68in3hma4v6er
            references rescue_centers,
    user_id          bigint       not null
        constraint fkifkx7se2ejg5sutq5b8d9ewip
            references users,
    constraint uk_rescue_review
        unique (rescue_center_id, user_id)
);

alter table rescue_center_reviews
    owner to pets_admin;

create table reviews
(
    id             bigint generated by default as identity
        primary key,
    comment        text,
    created_at     timestamp(6) not null,
    rating         integer      not null,
    reviewer_id    bigint       not null
        constraint fkd1isgfajhtdl8mgg29up6mofi
            references users,
    target_user_id bigint       not null
        constraint fki1sktfpjrk7gqmcshcinv3m0j
            references users
);

alter table reviews
    owner to pets_admin;

create table vaccinations
(
    id               bigint generated by default as identity
        primary key,
    clinic           varchar(255),
    created_at       timestamp(6) not null,
    name             varchar(255) not null,
    next_due_date    timestamp(6),
    notes            text,
    vaccination_date timestamp(6) not null,
    veterinarian     varchar(255),
    health_record_id bigint       not null
        constraint fksgeu4ptwru6gnbu2095ts5mq6
            references pet_health_records
);

alter table vaccinations
    owner to pets_admin;

create table weight_tracking
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6)     not null,
    notes            text,
    record_date      timestamp(6)     not null,
    weight           double precision not null,
    health_record_id bigint           not null
        constraint fk4kxjr6xjlh92lx2dy0n44mdu
            references pet_health_records
);

alter table weight_tracking
    owner to pets_admin;

