import type { FundraisingCampaign, Donation } from "@/lib/types"

export const fundraisingCampaigns: FundraisingCampaign[] = [
  {
    id: "campaign-1",
    title: "Cứu chó Husky bị tai nạn",
    slug: "cuu-cho-husky-tai-nan",
    description: "Giúp chó Husky bị tai nạn được chữa trị và phục hồi",
    image: "https:
    category: "medical",
    targetAmount: 5000000,
    currentAmount: 3500000,
    currency: "VND",
    createdBy: {
      id: "user-1",
      name: "Nguyễn Văn A",
      avatar: "https:
    },
    relatedPet: {
      id: "pet-1",
      name: "Max",
      image: "https:
    },
    status: "active",
    startDate: "2024-11-01T00:00:00Z",
    endDate: "2024-12-31T23:59:59Z",
    createdAt: "2024-11-01T00:00:00Z",
    updatedAt: "2024-12-10T10:00:00Z",
    description_detailed: "Max là chú Husky bị tai nạn giao thông vào ngày 31/10. Chú cần phẫu thuật và phục hồi trong thời gian dài. Mỗi đóng góp sẽ giúp Max có cơ hội sống lại.",
    beneficiary: "Trạm Cứu Hộ PetAid",
    updates: [
      {
        id: "update-1",
        campaignId: "campaign-1",
        title: "Max đã qua phẫu thuật thành công",
        content: "Sau 3 giờ phẫu thuật, Max đã tỉnh dậy an toàn. Các bác sĩ thú y cho biết tiên lượng rất tốt.",
        createdAt: "2024-12-08T14:30:00Z",
        images: ["https:
      },
    ],
  },
  {
    id: "campaign-2",
    title: "Xây dựng trung tâm cứu hộ mới",
    slug: "xay-dung-trung-tam-cuu-ho",
    description: "Giúp xây dựng một trung tâm cứu hộ hiện đại và khang trang",
    image: "https:
    category: "shelter",
    targetAmount: 50000000,
    currentAmount: 28500000,
    currency: "VND",
    createdBy: {
      id: "org-1",
      name: "Trạm Cứu Hộ PetAid",
      avatar: "https:
    },
    status: "active",
    startDate: "2024-10-01T00:00:00Z",
    endDate: "2025-03-31T23:59:59Z",
    createdAt: "2024-10-01T00:00:00Z",
    updatedAt: "2024-12-10T10:00:00Z",
    description_detailed: "Chúng tôi đang xây dựng một trung tâm cứu hộ mới với các tiện nghi đầy đủ để chăm sóc tốt hơn cho các thú cưng bị bỏ rơi.",
    beneficiary: "Trạm Cứu Hộ PetAid",
  },
  {
    id: "campaign-3",
    title: "Kiêm tiêm cho các mèo hoang",
    slug: "kiem-tiem-meo-hoang",
    description: "Chiến dịch kiêm tiêm vaccine cho các mèo hoang để ngăn ngừa dịch bệnh",
    image: "https:
    category: "medical",
    targetAmount: 2000000,
    currentAmount: 1800000,
    currency: "VND",
    createdBy: {
      id: "user-2",
      name: "Trần Thị B",
      avatar: "https:
    },
    status: "active",
    startDate: "2024-11-15T00:00:00Z",
    endDate: "2024-12-31T23:59:59Z",
    createdAt: "2024-11-15T00:00:00Z",
    updatedAt: "2024-12-10T10:00:00Z",
    description_detailed: "Chiến dịch này nhằm tiêm chủng cho các mèo hoang ở khu vực Quận 1 và Quận 3 để ngăn chặn các bệnh truyền nhiễm.",
    beneficiary: "Hiệp hội Bảo vệ Động vật",
  },
  {
    id: "campaign-4",
    title: "Hỗ trợ thực phẩm cho chó mồ côi",
    slug: "ho-tro-thuc-pham-cho-meo",
    description: "Cung cấp thức ăn, sữa cho các chó con mồ côi tại trạm cứu hộ",
    image: "https:
    category: "food",
    targetAmount: 1000000,
    currentAmount: 950000,
    currency: "VND",
    createdBy: {
      id: "org-1",
      name: "Trạm Cứu Hộ PetAid",
      avatar: "https:
    },
    status: "active",
    startDate: "2024-12-01T00:00:00Z",
    endDate: "2025-01-31T23:59:59Z",
    createdAt: "2024-12-01T00:00:00Z",
    updatedAt: "2024-12-10T10:00:00Z",
    description_detailed: "Chiến dịch hỗ trợ thực phẩm chuyên biệt cho các chó con mồ côi tuổi từ 1-3 tháng.",
    beneficiary: "Trạm Cứu Hộ PetAid",
  },
]

export const donations: Donation[] = [
  {
    id: "donation-1",
    campaignId: "campaign-1",
    donorId: "user-3",
    amount: 500000,
    currency: "VND",
    message: "Cố lên Max ơi!",
    isAnonymous: false,
    paymentMethod: "momo",
    status: "completed",
    createdAt: "2024-12-08T10:30:00Z",
  },
  {
    id: "donation-2",
    campaignId: "campaign-1",
    donorId: undefined,
    amount: 250000,
    currency: "VND",
    message: undefined,
    isAnonymous: true,
    paymentMethod: "zalopay",
    status: "completed",
    createdAt: "2024-12-07T15:45:00Z",
  },
  {
    id: "donation-3",
    campaignId: "campaign-1",
    donorId: "user-4",
    amount: 1000000,
    currency: "VND",
    message: "Chúc Max mau khỏe",
    isAnonymous: false,
    paymentMethod: "bank",
    status: "completed",
    createdAt: "2024-12-06T09:20:00Z",
  },
  {
    id: "donation-4",
    campaignId: "campaign-2",
    donorId: "user-5",
    amount: 2000000,
    currency: "VND",
    message: "Ủng hộ dự án",
    isAnonymous: false,
    paymentMethod: "card",
    status: "completed",
    createdAt: "2024-12-05T11:00:00Z",
  },
  {
    id: "donation-5",
    campaignId: "campaign-3",
    donorId: undefined,
    amount: 100000,
    currency: "VND",
    message: undefined,
    isAnonymous: true,
    paymentMethod: "momo",
    status: "completed",
    createdAt: "2024-12-04T14:30:00Z",
  },
]
