import type { PetPost } from './types';

export const mockPosts: PetPost[] = [
  {
    id: '1',
    title: 'Tìm chú Husky mất tích tại Quận 1 🐕',
    slug: 'tim-chu-husky-mat-tich',
    description: 'Chú Husky tên Max, lông xám trắng, đeo vòng cổ xanh dương. Mất tích chiều 3/1 tại công viên Lê Văn Tám. Ai nhìn thấy xin liên hệ ngay! 😢',
    image: 'https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=800',
    petType: 'Husky',
    status: 'lost',
    postType: 'LOST_FOUND',
    location: 'Công viên Lê Văn Tám, Q1',
    city: 'TP. Hồ Chí Minh',
    district: 'Quận 1',
    postedBy: {
      id: '1',
      name: 'Nguyễn Văn An',
      phone: '0912345678',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100',
      isVerified: false,
    },
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    tags: ['thatlac', 'husky', 'quan1', 'urgent'],
    views: 1234,
    featured: true,
    reactionCount: 45,
    favoriteCount: 12,
    commentCount: 23,
    userReaction: null,
    isFavorited: false,
    meta: {},
  },
  {
    id: '2',
    title: 'Review Phòng Khám Thú Y Sài Gòn PetCare ⭐⭐⭐⭐⭐',
    slug: 'review-phong-kham-saigon-petcare',
    description: 'Vừa đưa bé Miu đi khám tại PetCare. Bác sĩ rất tận tâm, giá cả hợp lý. Phòng khám sạch sẽ, thoáng mát. Mọi người nên đưa bé đi đây! 🏥💕',
    image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=800',
    petType: 'Mèo',
    status: 'general',
    postType: 'REVIEW',
    location: 'Bình Thạnh',
    city: 'TP. Hồ Chí Minh',
    district: 'Bình Thạnh',
    postedBy: {
      id: '2',
      name: 'Trần Thị Bảo',
      phone: '0987654321',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
      isVerified: true,
    },
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    tags: ['review', 'phongkham', 'binhthnh'],
    views: 567,
    reactionCount: 89,
    favoriteCount: 34,
    commentCount: 15,
    userReaction: 'LOVE',
    isFavorited: true,
    meta: {
      rating: 4.8,
      serviceName: 'Phòng Khám Thú Y Sài Gòn PetCare',
      visitDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      pros: ['Bác sĩ tận tâm', 'Giá cả hợp lý', 'Phòng khám sạch sẽ', 'Có chỗ đậu xe'],
      cons: ['Đông khách vào cuối tuần'],
      wouldRecommend: true,
    },
  },
  {
    id: '3',
    title: 'Bé Golden 2 tháng tuổi cần tìm nhà mới 🏠💛',
    slug: 'be-golden-can-tim-nha',
    description: 'Gia đình mình chuyển công tác nên cần tìm nhà yêu thương cho bé Golden. Bé 2 tháng tuổi, đã tiêm phòng đầy đủ, rất khỏe mạnh và ngoan. FREE nhận nuôi cho gia đình có trách nhiệm! 🐶',
    image: 'https://images.unsplash.com/photo-1633566137282-a8c8c0c1c2f0?w=800',
    petType: 'Golden Retriever',
    status: 'for-adoption',
    postType: 'ADOPTION',
    location: 'Quận 7',
    city: 'TP. Hồ Chí Minh',
    district: 'Quận 7',
    postedBy: {
      id: '3',
      name: 'Lê Minh Cường',
      phone: '0901234567',
      avatar: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=100',
      isVerified: false,
    },
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    tags: ['nhannuoi', 'golden', 'free', 'quan7'],
    views: 2341,
    featured: true,
    reactionCount: 234,
    favoriteCount: 89,
    commentCount: 67,
    userReaction: 'CARE',
    isFavorited: false,
    meta: {},
  },
  {
    id: '4',
    title: '[Bác Sĩ Chia Sẻ] 5 Dấu Hiệu Chó Mèo Cần Đi Khám Ngay 🩺',
    slug: 'bs-5-dau-hieu-cho-meo-can-kham',
    description: 'Là bác sĩ thú y 10 năm kinh nghiệm, mình muốn chia sẻ 5 dấu hiệu quan trọng các sen cần chú ý. Nếu thấy bé có những triệu chứng này, hãy đưa đến bác sĩ ngay nhé! 🏥',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800',
    petType: 'Chung',
    status: 'general',
    postType: 'TIP',
    location: 'Toàn quốc',
    city: 'TP. Hồ Chí Minh',
    district: null,
    postedBy: {
      id: '4',
      name: 'BS. Nguyễn Thu Hương',
      phone: '0912345678',
      avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=100',
      isVerified: true,
    },
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    tags: ['meohay', 'bacsi', 'suckhoe', 'kinhnghiem'],
    views: 5678,
    featured: true,
    reactionCount: 456,
    favoriteCount: 234,
    commentCount: 123,
    userReaction: null,
    isFavorited: true,
    meta: {
      category: 'Sức khỏe',
      readTime: 5,
      difficulty: 'easy',
      tipTags: ['suckhoe', 'chamsoс', 'phongbenh'],
    },
  },
  {
    id: '5',
    title: 'Hỏi: Mèo bị ghẻ tai phải làm sao? 😿',
    slug: 'hoi-meo-bi-ghe-tai',
    description: 'Mèo nhà mình gãi tai liên tục và có mùi hôi. Đã vệ sinh nhưng vẫn không khỏi. Các bạn có kinh nghiệm xin chỉ cho mình với ạ! Cảm ơn mọi người! 🙏',
    image: 'https://images.unsplash.com/photo-1573865526739-10c1dd4bc990?w=800',
    petType: 'Mèo',
    status: 'general',
    postType: 'QNA',
    location: 'Quận 3',
    city: 'TP. Hồ Chí Minh',
    district: 'Quận 3',
    postedBy: {
      id: '5',
      name: 'Phạm Thị Lan',
      phone: '0923456789',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
      isVerified: false,
    },
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['hoidap', 'meo', 'suckhoe', 'ghetai'],
    views: 890,
    reactionCount: 23,
    favoriteCount: 12,
    commentCount: 34,
    userReaction: null,
    isFavorited: false,
    meta: {
      topic: 'Sức khỏe',
      difficulty: 'intermediate',
      isAnswered: true,
      answerCount: 34,
      expertAnswered: true,
    },
  },
  {
    id: '6',
    title: 'Thanh Lý Chuồng Mèo 3 Tầng - Như Mới 🏰',
    slug: 'thanh-ly-chuong-meo-3-tang',
    description: 'Do nhà mới không gian nhỏ nên thanh lý chuồng mèo 3 tầng. Mua 3 triệu, xài 2 tháng như mới, bán 1.5 triệu. Tặng kèm nệm và đồ chơi. Quận 9 nhé! 📦',
    image: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=800',
    petType: 'Mèo',
    status: 'general',
    postType: 'MARKETPLACE',
    location: 'Quận 9',
    city: 'TP. Hồ Chí Minh',
    district: 'Quận 9',
    postedBy: {
      id: '6',
      name: 'Võ Hoàng Kim',
      phone: '0934567890',
      avatar: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=100',
      isVerified: false,
    },
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['chodo', 'chuongmeo', 'thanhly', 'quan9'],
    views: 456,
    reactionCount: 34,
    favoriteCount: 23,
    commentCount: 12,
    userReaction: null,
    isFavorited: false,
    meta: {
      price: 1500000,
      originalPrice: 3000000,
      currency: 'VND',
      condition: 'like-new',
      category: 'Phụ kiện',
      pickupMethod: 'both',
      location: 'Quận 9, TP.HCM',
      inStock: true,
    },
  },
  {
    id: '7',
    title: 'Tìm bạn đời cho Husky đực 2 tuổi 💕🐕',
    slug: 'tim-ban-doi-cho-husky',
    description: 'Tìm bạn gái Husky thuần chủng cho Max nhà mình. Max 2 tuổi, đã tiêm phòng đầy đủ, có giấy chứng nhận sức khỏe. Hy vọng tìm được bạn gái phù hợp! 🎀',
    image: 'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800',
    petType: 'Husky',
    status: 'general',
    postType: 'BREEDING',
    location: 'Quận 1',
    city: 'TP. Hồ Chí Minh',
    district: 'Quận 1',
    postedBy: {
      id: '1',
      name: 'Nguyễn Văn An',
      phone: '0912345678',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100',
      isVerified: false,
    },
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['phoigiong', 'husky', 'quan1'],
    views: 234,
    reactionCount: 12,
    favoriteCount: 8,
    commentCount: 5,
    userReaction: null,
    isFavorited: false,
    meta: {
      petBreed: 'Husky Siberian',
      petGender: 'male',
      age: 24,
      isNeutered: false,
      isVaccinated: true,
      healthCertified: true,
      lookingFor: 'Husky cái thuần chủng, 18-36 tháng',
      requirements: ['Có giấy chứng nhận sức khỏe', 'Đã tiêm phòng đầy đủ', 'Có thể gặp trước để làm quen'],
      fee: 0,
    },
  },
];
